### PR TITLE
Added a option to rewritePaths to be able to use local packages with their full name

### PR DESCRIPTION
**Pull request by JoelBonnier**
This repository was forked to solve a problem with using the full path of a packages.

The problem is that the loader does not support package names to be resolved correctly. We added a rewrite function that gets it props from the options of the loader. The option `options.rewritePath` that takes an array of package names to replace so it can be loaded correctly in storybook. `@bonniernews/dn-web-components/button/button.njk` -> `button/button.njk`

As the package names are very specific we did not add any logic to verify that it is a path that we are changing.

### CODE REVIEW

**Comment by ogonkov** [comment]
Hello, thank you for your interest in my package!

Does `require.resolve('@bonniernews/dn-web-components')` resolved to absolute path by nodejs?

**Comment by JoelBonnier** [comment]
> Hello, thank you for your interest in my package!
> 
> Does `require.resolve('@bonniernews/dn-web-components')` resolved to absolute path by nodejs?

Thanks for a great loader @ogonkov! 

Our problem is that we are building a design system package that should be used in other applications. There we need to reference all templates with the full package name to make the import work, eg . `@bonniernews/dn-web-components/button/button.njk`. 

The require.resolve gives the absolute path for that package and it is correct. But this is not our issue (I tried the solution that was in your closed issue.) . We can find the template correctly if we use `button/button.njk` so the import works. But as we need to reference it with the package name we get we get the error that it cannot find the template when we run our storybook.

I would be happy if we could use your loader without modifications but I think this is a use case that is not supported at the moment. But I might be mistaken.

**Comment by ogonkov** [comment]
I believe that your problem should be covered by `searchPaths` option

```js
{
  "searchPaths": [
    require.resolve("@bonniernews/dn-web-components"),
    "."
  ]
}
```

**Comment by ogonkov** [comment]
I was wrong

**Pull request merged**
